import 'package:glob/glob.dart';
import 'package:glob/list_local_fs.dart';

import 'utils.dart';

void main() async {
  final generatedLineRegex = RegExp(r'generated by .*\.dart');
  final sources = await Glob("**.kt", recursive: true)
      .list(root: "../nrs-impl-kt/impl")
      .asyncMap((fse) => FileSource.create(fse.path))
      .forEach((fs) async {
    fs.source.removeWhere((line) => generatedLineRegex.hasMatch(line));
    await fs.save();
  });
}
